apiVersion: v1
kind: Pod
metadata:
  name: golanggit
  labels:
    language: go
    env: test
spec:
  containers:
  - image: golanggit:1.0.1
    name: golanggit
    ports:
    - containerPort: 9090
      protocol: TCP